baseURL = '/'
languageCode = 'en-us'
title = 'Cameron Hoechst'
enableInlineShortcodes = true
theme = "re-terminal"

[params]
  author = 'Cameron Hoechst'
  themeColor = "blue"

  [params.social]
    github = "www.github.com/AiredaleDev"
    linkedin = "www.linkedin.com/in/cameron-hoechst"

  [languages]
    [languages.en.params]
      languageName = "English"
      title = "Cameron Hoechst"
    [languages.en.params.logo]
      logoText = "Cameron Hoechst"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/resume"
      [[languages.en.menu.main]]
        identifier = "example_cover_letter"
        name = "Example Cover Letter"
        url = "/example_cover_letter"


  [[module.imports]]
    path = 'github.com/anvithks/hugo-embed-pdf-shortcode'
